(define (make-account balance password)
	(define error-count 0)
	(define call-count 0)
	(define (withdraw amount)
		(if (>= balance amount)
			(begin (set! balance (- balance amount))
				balance)
			"Insufficient funds"))
	(define (deposit amount)
		(set! balance (+ balance amount))
		balance)
	(define (call-the-cops)
		(display "Calling the cops")
		(error "too many error passwords"))
	(define (reset-error)
		(set! error-count 0))
	(define (add-call)
		(set! call-count (+ 1 call-count)))
	(define (displayIndex)
		(error "already call " call-count))
	(define (error-dispay)
		(set! error-count (+ 1 error-count))
		(if (> error-count 7)
			(call-the-cops)
			(display "Incorrent password -- MAKE-ACCOUNT")))
	(define (dispatch inputPassword m )
		(add-call)
		(if (eq? password inputPassword)
				(cond ((eq? m 'withdraw) reset-error withdraw)
					((eq? m 'deposit) reset-error deposit)
					((eq? m 'how-many-calls) displayIndex)
					(else (display "Unknow request -- MAKE-ACCOUNT" m)))
			(error-dispay)))
	dispatch)